; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0 

	TITLE	C:\Users\Jeter\Desktop\Code\Code\Visual Studio\DotProductIndex\DotProductIndex\DotProductIndex\DotProductIndex.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?DotProductIndex@@YAXQAH0H@Z			; DotProductIndex
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
; rtc$TMZ	SEGMENT                               ; Remove
; __RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown   ; Remove
; rtc$TMZ	ENDS                                  ; Remove
;	COMDAT rtc$IMZ
; rtc$IMZ	SEGMENT                               ; Remove
; __RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase   ; Remove
; rtc$IMZ	ENDS                                  ; Remove
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?DotProductIndex@@YAXQAH0H@Z
_TEXT	SEGMENT
_sum$ = -20						; size = 4
_i$ = -8						; size = 4
_ArrayA$ = 8						; size = 4
_ArrayB$ = 12						; size = 4
_n$ = 16						; size = 4
?DotProductIndex@@YAXQAH0H@Z PROC			; DotProductIndex, COMDAT
; File c:\users\Jeter\desktop\code\code\visual studio\dotproductindex\dotproductindex\dotproductindex\dotproductindex.cpp
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 6
	mov	DWORD PTR _sum$[ebp], 0
; Line 7
;	mov	DWORD PTR _i$[ebp], 0             ; Remove
    mov eax, 0                            ; initialize i in eax
	mov edx, DWORD PTR _n$[ebp]           ; move n into edx
	jmp	SHORT $LN4@DotProduct
$LN2@DotProduct:
;	mov	eax, DWORD PTR _i$[ebp]           ; Remove
	add	eax, 1
;	mov	DWORD PTR _i$[ebp], eax
$LN4@DotProduct:
;	mov	eax, DWORD PTR _i$[ebp]           ; Remove
;	cmp	eax, DWORD PTR _n$[ebp]           ; Remove and replace with:
    cmp eax, edx
	jge	SHORT $LN1@DotProduct
; Line 9
;	mov	eax, DWORD PTR _i$[ebp]           ; Remove
	mov	ecx, DWORD PTR _ArrayA$[ebp]
;	mov	edx, DWORD PTR _i$[ebp]           ; Remove
;	mov	esi, DWORD PTR _ArrayB$[ebp]      ; Remove
;	mov	eax, DWORD PTR [ecx+eax*4]        ; Remove
    mov esi, DWORD PTR [ecx+eax*4]        ; ArrayA[i]
    mov ecx, DWORD PTR _ArrayB$[ebp]      ; use ecx instead of esi
;	imul	eax, DWORD PTR [esi+edx*4]
    imul esi, DWORD PTR [ecx+eax*4]
;	add	eax, DWORD PTR _sum$[ebp]
    add esi, DWORD PTR _sum$[ebp]
;	mov	DWORD PTR _sum$[ebp], eax
    mov DWORD PTR _sum$[ebp], esi
; Line 10
	jmp	SHORT $LN2@DotProduct
$LN1@DotProduct:
; Line 12
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?DotProductIndex@@YAXQAH0H@Z ENDP			; DotProductIndex
_TEXT	ENDS
END
