; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0

	TITLE	C:\Users\Jeter\Desktop\Code\Visual Studio\DotProductPointer\DotProductPointer\DotProductPointer\DotProductPointer.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?DotProductPointer@@YAXPAH0H@Z			; DotProductPointer
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
 rtc$TMZ	SEGMENT
 __RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
 rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
 rtc$IMZ	SEGMENT
 __RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
 rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?DotProductPointer@@YAXPAH0H@Z
_TEXT	SEGMENT
_sum$ = -20						; size = 4
_i$ = -8						; size = 4
_ArrayA$ = 8						; size = 4
_ArrayB$ = 12						; size = 4
_n$ = 16						; size = 4
?DotProductPointer@@YAXPAH0H@Z PROC			; DotProductPointer, COMDAT
; File c:\users\jeter\desktop\code\visual studio\dotproductpointer\dotproductpointer\dotproductpointer\dotproductpointer.cpp
; Line 5
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 7
	mov	DWORD PTR _sum$[ebp], 0
; Line 8
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN4@DotProduct
$LN2@DotProduct:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN4@DotProduct:
	mov	eax, DWORD PTR _i$[ebp]
	cmp	eax, DWORD PTR _n$[ebp]
	jge	SHORT $LN1@DotProduct
; Line 10
	mov	eax, DWORD PTR _i$[ebp]
	mov	ecx, DWORD PTR _ArrayA$[ebp]
	mov	edx, DWORD PTR _i$[ebp]
	mov	esi, DWORD PTR _ArrayB$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4]
	imul	eax, DWORD PTR [esi+edx*4]
	mov	ecx, DWORD PTR _sum$[ebp]
	lea	edx, DWORD PTR [ecx+eax*4]
	mov	DWORD PTR _sum$[ebp], edx
; Line 11
	jmp	SHORT $LN2@DotProduct
$LN1@DotProduct:
; Line 13
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?DotProductPointer@@YAXPAH0H@Z ENDP			; DotProductPointer
_TEXT	ENDS
END
